[package]
name = "ogc-rs"
version = "0.7.1"
authors = ["rust-wii"]
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
ffi = []

[dependencies]
bitflags = "1.3"
num_enum = { version = "0.5", default-features = false }
cfg-if = "1.0"
cstr_core = "0.2"

libm = "0.2"
libc = "0.2"
ogc-sys = { version = "0.4.2", path = "ogc-sys" }
glam = { version = "0.19.0", default-features = false, features = ["libm"], optional = true }
voladdress = "0.4"
#lock_api = "0.4.5"
