[package]
name = "ogc-rs"
version = "0.5.0"
authors = ["rust-wii"]
edition = "2018"

[lib]
crate-type = ["rlib"]
name = "ogc"

[dependencies]
bitflags = "1.1"
enum-primitive-derive = "0.1"
num-traits = "0.2"

[dependencies.ogc-sys]
path = "../ogc-sys"

