[package]
name = "ogc-rs"
version = "0.1.0"
authors = ["rust-wii"]
edition = "2018"

[lib]
crate-type = ["rlib"]
name = "ogc"

[dependencies]
bitflags = "1.1"

[dependencies.ogc-sys]
path = "../ogc-sys"
version = "0.1"

